### ISSUE TITLE
App seems to be broken on Android 8.0.1

### ISSUE THREAD

**Issue by shridharkalagi** [cloudgrey-io/the-app#1]
App seems to be broken on Android 8.0.1. Screenshots taken on One Plus 6 mobile. 
App - TheApp-v1.6.1.apk

![webview](https://user-images.githubusercontent.com/18380219/44722993-69de9a00-aaec-11e8-9c72-d5d32d4d054b.jpeg)
![cc](https://user-images.githubusercontent.com/18380219/44722994-69de9a00-aaec-11e8-8805-11ffa3278fca.jpeg)
![login](https://user-images.githubusercontent.com/18380219/44722995-69de9a00-aaec-11e8-955f-c0a702a41f11.jpeg)
![echo](https://user-images.githubusercontent.com/18380219/44722996-6a773080-aaec-11e8-9760-4565dcf93a7c.jpeg)

**Comment by shridharkalagi** [comment]
@jlipps any update please?

**Comment by jlipps** [comment]
hi @shridharkalagi yes this is a known issue. it is just cosmetic (the field still works, you just can't see the letters), and i will try and fix it.

**Comment by jlipps** [comment]
OK the text field issue has been fixed.
