### ISSUE TITLE
TheApp 1.10.0 .apk is not supporting Android 12 

### ISSUE THREAD

**Issue by svermagit** [cloudgrey-io/the-app#3]
The new Andorid 12 is not supporting latest theApp 1.10.0 apk, is there any version available which is compatible to Android 12? If yes could you please share

**Comment by jlipps** [comment]
the app is no longer being developed here. it is now at https://github.com/appium-pro/the-app. however it is in the middle of a complete rewrite based on react native updates. i've been having trouble getting it building on ios but the android build is working, at least for several of the screens. you could try building that project to run on android 12.
